### PR TITLE
Remove arm32

### PR DESCRIPTION
**Pull request by phil-davis**
https://cloud.drone.io/owncloud-ci/php/34/18/5
`arm32v7-v7.2: Error: No such image: docker.io/owncloud/ubuntu:latest`

IMO there is no longer an `owncloud/ubuntu:latest` for 32-bit. So we [may as well|should|have to] remove the equivalent here in `owncloud-ci/php`

### CODE REVIEW

**Comment by xoxys** [comment]
Related to: https://github.com/owncloud-docker/ubuntu/pull/38#issuecomment-634440477

**Comment by phil-davis** [comment]
drone has not started, maybe I am somehow not "connected" nicely to the drone server for this?
@xoxys

**Comment by xoxys** [comment]
@phil-davis Fixed. Webhook integration broken...

**Comment by phil-davis** [comment]
Note: by rebuilding this, we will get the latest PHP patch releases from yesterday:
https://www.php.net/downloads.php
PHP 7.4.7 and 7.3.19
Which is "a good thing" (tm)

That is what got me looking in this repo, and then discovering that the 32-bit builds are now broken.

**Comment by xoxys** [comment]
We could add a nightly/weekly/... trigger to rebuild the container from time to time?

**Comment by phil-davis** [comment]
> We could add a nightly/weekly/... trigger to rebuild the container from time to time?

PHP patch releases come out monthly. `@monthly` would be fine. We have never had real urgency to get the latest PHP patch release in CI, but it is nice that it does not get "too far" behind.

**Comment by xoxys** [comment]
Let's do it.

grafik

**Comment by phil-davis** [comment]
The monthly cron has not been running. I restarted an old merge job just now: https://cloud.drone.io/owncloud-ci/php/38
That should produce new docker images, which will have the latest patch releases of PHP.
And it should include the latest version of composer, which will avoid messages like: https://drone.owncloud.com/owncloud/brute_force_protection/1186/1/2
```
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.
```

**Comment by xoxys** [comment]
@phil-davis That's because I was too stupid to notice that owncloud-ci is running on cloud. Cron is (and was never) supported on cloud. We should migrate CI to internal drone as well or live with it.

**Comment by phil-davis** [comment]
We can live with it. `owncloud-ci` runs only a few builds, I doubt that it will get blocked.

**Pull request merged**
