### PR TITLE
Remove 'latest' owncloudci/php

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #137 

The `latest` image is "old" anyway, and all the CI explicitly specifies a PHP version for all pipelines. So remove `latest` to avoid confusion.

### CODE REVIEW

**Review by TheRealBro — COMMENTED** [review]
Fine for me, not sure if it breaks any pipeline if we just remove it without offering anything named "latest" - waiting for approval from @xoxys

**Review by xoxys — APPROVED** [review]
If something breaks, it needs to be fixed afterwards. I'm going to remove the latest tag from docker hub as well to avoid any further usage.

**Comment by phil-davis** [comment]
Merging - lots of nightly CI will run tonight, and we will soon know of anything that tried to use `latest`. Actually, I will be surprised if anything breaks.

**Comment by voroyam** [comment]
please notify me or @d7oc to keep us in the loop regarding changes in the pipelines. This is the second time that something (tm) breaks the BayernBox pipeline and I find an issue where neither of us has been included that caused the issue. (yes, the fist time there was a notification as a reply to a Rocket Chat notification)

**Pull request merged**
