### PR TITLE
install php-ldap

### PR DESCRIPTION
**Pull request by individual-it**
need to be able to use this image to run tests on the `user_ldap` app

### CODE REVIEW

**Comment by patrickjahns** [comment]
Please send backports for the other PHP versions - 👍

**Comment by individual-it** [comment]
trying to build the docker container on any other branch than master I get: 
```
Step 6/15 : RUN apt-get update -y &&   apt-get install -y software-properties-common language-pack-en-base &&   LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php &&   LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/apache2
 ---> Running in 22488a66547c
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [57.3 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [553 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [252 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3492 B]
Get:9 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [238 kB]
Err:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources
  Hash Sum mismatch
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [917 kB]
Err:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
  
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [744 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.5 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [5162 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7146 B]
Fetched 24.8 MB in 31s (790 kB/s)
Reading package lists...
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/source/by-hash/SHA256/491652e6aa9bdac6739de39dc6c82093b89e9f754e4b733c227f4758214910c0  Hash Sum mismatch
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/3456ef1d0de1ba302945eb8c59c8dffb221794d808cf5a0c53e675a765692b72  
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update -y &&   apt-get install -y software-properties-common language-pack-en-base &&   LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php &&   LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/apache2' returned a non-zero code: 100
Makefile:13: die Regel für Ziel „build“ scheiterte
make: *** [build] Fehler 100
```

**Comment by patrickjahns** [comment]
Does it fail locally or on drone?

**Comment by individual-it** [comment]
locally, haven't tried pushing. Thought no need to try it if it does not build locally

**Comment by patrickjahns** [comment]
well it looks like a hashsum / mirror fuck up - just tried with 5.6 branch locally and it worked for me 🤷‍♂️

**Comment by individual-it** [comment]
backports in #28 #29 #30 #31

**Pull request merged**
