### PR TITLE
Enable openssl legacy

### PR DESCRIPTION
**Pull request by phil-davis**
Ubuntu 22.04 has openssl v3. openssl v3 disables various legacy encryption methods. For the current oC10 encryption app, we need those legacy encryption methods to be available.

This PR provides an `etc/ssl/opensssl.cnf` that has the legacy encryption methods enabled.

Ref: https://github.com/owncloud/core/pull/40745 tries to run core CI with Ubuntu 22.04 docker.
Related core issue https://github.com/owncloud/core/issues/40071
Documentation about how production Ubuntu 22.04 systems enable the legacy encryption methods: https://doc.owncloud.com/server/10.12/admin_manual/installation/manual_installation/manual_installation_prerequisites.html#openssl-version

### CODE REVIEW

**Comment by phil-davis** [comment]
@xoxys is this the way to achieve this? Or is there a different way it should be done?

**Comment by xoxys** [comment]
IMO, we should not use Ubuntu 22 for anything related to oc10. We add more and more hacks and workarounds to get it working somehow (PHP, OpenSSL, etc.). Sticking to Ubuntu 20.04 as long as possible, especially for the production containers `owncloud/server` and `owncloud/appliance` I would not recommend the switch to Ubuntu 22.

However, if the legacy stuff is really required, yes I guess that's the way to go even if I have not tested/verified it.

**Comment by xoxys** [comment]
Don't know the details, but is it really a good idea to tell people to use the legacy mode instead of fixing the code to support a modern OpenSSL version?

**Comment by phil-davis** [comment]
We have the`owncloud-ci/php` container versions for Ubuntu 22.04 so it would be nice to apply the customisations that we know about. That way those container versions can be used to "easily" check the Ubuntu 22.04 + PHP 7.4 + ownCloud10 combination.

https://doc.owncloud.com/server/next/admin_manual/installation/system_requirements.html#officially-supported-environments lists Ubuntu 20.04 and 22.04 - so if 22.04 is not to be supported, that would need to be discussed.

**Review by xoxys — APPROVED** [review]
Ok for me. But shouldn't the CI fail as expected as long as the encryption app is not fixed properly? The legacy mode might be a workaround for existing deployments, but it's still just a workaround and not a proper fix. However, don't want to block you, feel free to merge.

**Comment by xoxys** [comment]
As there are no plans to fix it, using the legacy mode is the only way.

**Pull request merged**
