### PR TITLE
Add PHP7.4

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #111 

Add PHP7.4

Is it really this easy?

I just copy-pasted all the 7.3 folder and occurrences in top-level files and changed to 7.4
And in the 2nd commit I renamed some sub-folders from 7.3 to 7.4

### CODE REVIEW

**Comment by phil-davis** [comment]
I guess the build here will also pick up the latest PHP 7.1 7.2 7.3 patch releases?

**Comment by phil-davis** [comment]
@tboerger can you either make those links, or give me some instruction about making the symlinks.
Otherwise I am likely to "do something random that I think is correct" and then you will have to tell me that I did it the wrong way and we will go around in circles for a while...

**Comment by tboerger** [comment]
change into the directoy of every 20-oci8.ini file, and execute `ln -sf ../../mods-available/oci8.ini 20-oci8.ini`. Maybe you also got to delete the file before, just try it.

**Comment by phil-davis** [comment]
@tboerger done, it worked easily deleting the "wrong" file first.
Should I squash?

**Comment by phil-davis** [comment]
@tboerger merge?
I don't have the power.

**Pull request merged**
