### PR TITLE
Bugfix/bring back oracle

### PR DESCRIPTION
**Pull request by DeepDiver1975**
oci 2.2.0 has been released - https://pecl.php.net/package-changelog.php?package=oci8&release=2.2.0

### CODE REVIEW

**Comment by tboerger** [comment]
All the configs had been symlinks to the mods folder.

**Comment by patrickjahns** [comment]
@DeepDiver1975 
Did you test the resulting image?

Wondering if we should establish a short test scenario in the drone pipeline to verify that the images work.

**Comment by DeepDiver1975** [comment]
> Wondering if we should establish a short test scenario in the drone pipeline to verify that the images work.

yes - we should do so ....

**Comment by DeepDiver1975** [comment]
> Did you test the resulting image?

No - we need to add a php7.3+oci step to core .... we will see ....

**Pull request merged**
